#ifndef OPM_GENERATED_OPM_TIMESTAMP_HEADER_INCLUDED
#define OPM_GENERATED_OPM_TIMESTAMP_HEADER_INCLUDED
#define BUILD_TIMESTAMP "2024-10-06 at 17:03:26 hrs"
#endif // OPM_GENERATED_OPM_TIMESTAMP_HEADER_INCLUDED
