#ifndef OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
#define OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
#define PROJECT_VERSION_NAME "2024.10-pre"
#define PROJECT_VERSION_HASH "debug"
#define PROJECT_VERSION "2024.10-pre (debug)"
#endif // OPM_GENERATED_OPM_VERSION_HEADER_INCLUDED
