#ifndef OPM_GENERATED_OPM_TIMESTAMP_HEADER_INCLUDED
#define OPM_GENERATED_OPM_TIMESTAMP_HEADER_INCLUDED
#define BUILD_TIMESTAMP "2024-10-03 at 18:17:49 hrs"
#endif // OPM_GENERATED_OPM_TIMESTAMP_HEADER_INCLUDED
